namespace Rotorwash.Sim;

/// <summary>
/// The complete physical description of one aircraft. Handwritten for the story
/// helicopters, generated by the block builder for player-made ones - either way the
/// flight model only reads this.
/// </summary>
public sealed class Airframe
{
    public string Name { get; set; } = "unnamed";

    public RotorConfig MainRotor { get; init; } = new();
    public TailRotorConfig TailRotor { get; init; } = new();
    public EngineConfig Engine { get; init; } = new();

    /// <summary>Structural, equipment and payload masses. Fuel is managed separately.</summary>
    public MassProperties Mass { get; } = new();

    public List<AeroSurface> Surfaces { get; } = new();

    /// <summary>
    /// Equivalent flat-plate drag area in each body axis, m^2. Forward is small on a
    /// clean airframe and enormous sideways - which is why a helicopter weathervanes
    /// and why sideways flight is limited.
    /// </summary>
    public Vec3 DragArea { get; set; } = new(2.1, 12.0, 9.0);

    /// <summary>Fuselage pitching/yawing moment slope with angle of attack and sideslip.</summary>
    public double FuselageCmAlpha { get; set; } = 0.9;
    public double FuselageCnBeta { get; set; } = -0.4;
    /// <summary>Reference length for the fuselage moments, m.</summary>
    public double ReferenceLength { get; set; } = 12.0;

    /// <summary>Fraction of rotor thrust lost to downwash pressing on the fuselage in the hover.</summary>
    public double VerticalDrag { get; set; } = 0.035;

    /// <summary>Usable fuel capacity, kg.</summary>
    public double FuelCapacity { get; set; } = 1100.0;

    /// <summary>Where the fuel sits, body FRD, m.</summary>
    public Vec3 FuelPosition { get; set; } = new(-0.4, 0, -0.3);

    /// <summary>Contact points for the headless ground model: skids or wheels.</summary>
    public List<Vec3> ContactPoints { get; } = new();

    /// <summary>Accessory and transmission losses as a fraction of main rotor power.</summary>
    public double DrivetrainLoss { get; set; } = 0.035;

    /// <summary>Never-exceed speed, m/s - advisory only, the aerodynamics do the punishing.</summary>
    public double Vne { get; set; } = 80.0;

    /// <summary>
    /// A medium utility twin in the Huey/Bell 212 class. Deliberately not a real
    /// aircraft: close enough that the numbers behave, different enough that it belongs
    /// to this world. This is the aircraft the player starts with.
    /// </summary>
    public static Airframe Workhorse()
    {
        var af = new Airframe
        {
            Name = "Workhorse",
            MainRotor = new RotorConfig
            {
                NumBlades = 2,
                Radius = 7.32,
                Chord = 0.58,
                RootCutout = 0.16,
                Twist = -0.16,
                HingeOffset = 0.0,            // teetering head: soft, laggy, forgiving
                BladeMass = 145.0,
                RotorInertia = 5200.0,
                NominalOmega = 33.9,          // ~324 rpm
                ShaftTiltForward = 0.087,
                HubPosition = new Vec3(0.05, 0, -2.35),
                CollectiveMax = 17.0 * Math.PI / 180.0,
                CyclicRange = 10.0 * Math.PI / 180.0,
                Blade = new Airfoil(),
            },
            TailRotor = new TailRotorConfig
            {
                NumBlades = 2,
                Radius = 1.30,
                Chord = 0.28,
                GearRatio = 5.9,
                Position = new Vec3(-8.6, 0, -1.1),
                PitchMax = 24.0 * Math.PI / 180.0,
            },
            Engine = new EngineConfig
            {
                MaxContinuousPower = 950_000,
                TakeoffPower = 1_050_000,
                TransmissionTorqueLimit = 30_000,
                SpoolTime = 0.7,
                Sfc = 9.2e-8,
            },
            DragArea = new Vec3(2.4, 13.5, 10.0),
            FuelCapacity = 800.0,
            FuelPosition = new Vec3(-0.15, 0, -0.35),
            Vne = 62.0,
        };

        // Laid out so the loaded centre of gravity sits within a few centimetres of the
        // mast. A helicopter hangs from its rotor: move the CG a handful of centimetres
        // and the pilot spends the whole flight holding cyclic against it, which is
        // exactly the trade the block builder will let players make - and regret.
        af.Mass.Add("cockpit", new Vec3(2.20, 0, -0.50), 380.0, new Vec3(160, 220, 220));
        af.Mass.Add("cabin", new Vec3(0.72, 0, -0.55), 1450.0, new Vec3(1400, 2600, 2400));
        af.Mass.Add("engine", new Vec3(-1.40, 0, -1.95), 320.0, new Vec3(60, 120, 110));
        af.Mass.Add("transmission", new Vec3(0.00, 0, -1.75), 250.0, new Vec3(40, 40, 40));
        af.Mass.Add("rotorhead", new Vec3(0.05, 0, -2.35), 420.0, new Vec3(900, 900, 1700));
        af.Mass.Add("tailboom", new Vec3(-5.20, 0, -0.95), 200.0, new Vec3(30, 900, 900));
        af.Mass.Add("tailrotor", new Vec3(-8.60, 0, -1.10), 60.0);
        af.Mass.Add("skids", new Vec3(0.10, 0, 1.00), 120.0, new Vec3(120, 200, 200));
        af.Mass.Add("pilot", new Vec3(2.00, -0.62, -0.25), 90.0);

        af.Surfaces.Add(new AeroSurface
        {
            Name = "horizontal_stabiliser",
            Position = new Vec3(-6.4, 0, -0.6),
            Normal = Vec3.Up,
            Area = 1.35,
            Incidence = -0.035,
            AspectRatio = 4.2,
            DownwashFactor = 0.55,
        });
        af.Surfaces.Add(new AeroSurface
        {
            Name = "vertical_fin",
            Position = new Vec3(-8.2, 0, -1.0),
            Normal = Vec3.Right,
            Area = 1.15,
            Incidence = 0.06,             // cambered to unload the tail rotor in cruise
            AspectRatio = 1.9,
        });

        af.ContactPoints.Add(new Vec3(1.55, -1.30, 1.15));
        af.ContactPoints.Add(new Vec3(1.55, 1.30, 1.15));
        af.ContactPoints.Add(new Vec3(-1.45, -1.30, 1.15));
        af.ContactPoints.Add(new Vec3(-1.45, 1.30, 1.15));

        return af;
    }
}
